# Generated by Django 3.2.7 on 2021-09-26 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='downvotes',
        ),
    ]
