# Generated by Django 3.2.7 on 2021-09-26 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartit', '0002_remove_film_downvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='films',
        ),
        migrations.CreateModel(
            name='FilmChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chartit.chart', verbose_name='Chart')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chartit.film', verbose_name='Film')),
            ],
        ),
        migrations.AddField(
            model_name='chart',
            name='films',
            field=models.ManyToManyField(through='chartit.FilmChart', to='chartit.Film'),
        ),
    ]
